### ISSUE TITLE
can requests library support chinese response in robot?

### ISSUE THREAD

**Issue by yongchao88** [bulkan/robotframework-requests#104]
![image](https://cloud.githubusercontent.com/assets/11289655/13845107/b188d152-ec78-11e5-85d2-a02af23a5d6c.png)

**Comment by yongchao88** [comment]
if the response have chinese content, that will cause mess code

**Comment by bulkan** [comment]
Can you provide a test case ? 

Pull requests are welcome

**Comment by yongchao88** [comment]
the case have some kind of secret, I just use it to send a request to a chinese website, then always cause mess code on it.

**Comment by bulkan** [comment]
Can you write a testcase against request https://httpbin.org/ ?

**Comment by bulkan** [comment]
No response from OP
