### ISSUE TITLE
Post request keyword troubles from version 0.4.2 upwards

### ISSUE THREAD

**Issue by arjenjobse** [bulkan/robotframework-requests#105]
Since update to version 0.4.2 my testcase doesn't work anymore.

My testcases:

_Requests-library updaten
    RequestsLibrary.Create Session    AWACS    ${awacs_url}
    ${request}=    Get Binary File    ../RobotFramework/Test_code/_Data/test01.xml
    ${requests}=    Create Dictionary    request=${request}
    ${resp}=    RequestsLibrary.Post Request    AWACS    ${awacs_uri}    ${requests}
    Delete All Sessions_

This gives me incorrect XML. Example in run log:
_Post Request using : alias=AWACS, uri=/anva/awacs/absagent, data=request=**%3C**AWACS**%3E**%3CHEADER%3E%3CSERVICE_ID%3EABSANVA%3C%2FSERVICE_ID%3E%3CDATASOURCE%3E1%3C%2FDATASOURCE%3E%3CKEY%2F%3E%3C%2FHEADER%3E%3CDATA%3E%3CREQUEST%3E%3CFUNCTION+NAME%3D%22 ..._

I can solve this by adding single quotes ('), but that doesn't work. I mean: _${resp}=    RequestsLibrary.Post Request    AWACS    ${awacs_uri}    '${requests}'_

The recieving side says he's missing the "request" parameter.

In the working version (previous versions like 0.4.1) it looks like this:
_Post Request using : alias=AWACS, uri=/anva/awacs/absagent, data='{u'request': '<AWACS><HEADER><SERVICE_ID>ABSANVA</SERVICE_ID><DATASOURCE>1</DATASOURCE><KEY/></HEADER><DATA><REQUEST> ..._

**Comment by arjenjobse** [comment]
And I found the solution: adding the content type in the header.

So I added:
_&{headers}=    Create Dictionary    Content-Type=application/x-www-form-urlencoded_

And I the Post Request is using the content type now:
_ ${resp}=    RequestsLibrary.Post Request    AWACS    ${awacs_uri}    data=${requests}    headers=${headers}_

**Comment by oleduc** [comment]
Hi,

Right now the content of the request is formatted according to the header type as you just found out by yourself.

If you ever encounter a situation where your content type is not implemented, please add a feature request or provide a pull request.

Thanks!
