### ISSUE TITLE
please help to confirm one confusion about the function: _format_data_according_to_header

### ISSUE THREAD

**Issue by bale836** [bulkan/robotframework-requests#108]
def _format_data_according_to_header(self, session, data, headers):
        headers = self._merge_headers(session, headers)

        if data is not None and headers is not None and 'Content-Type' in headers and **not self._is_json(data)**:
            if headers['Content-Type'].find("application/json") != -1:
                data = json.dumps(data)
            elif headers['Content-Type'].find("application/x-www-form-urlencoded") != -1:
                data = self._utf8_urlencode(data)
        else:
            data = self._utf8_urlencode(data)

        return data

I think there is one mistake about "not self._is_json(data)", if not json, then it is not necessary to json.dumps(data), so i think i should be "and self._is_json(data)", i am not sure i understand your desgin, please help to confirm, thanks.

I modify it locally, it can process json succesfully, otherwise, the json data will be prcessed as String.

**Comment by bulkan** [comment]
@vkosuri can you please help with this ?

**Comment by vkosuri** [comment]
@bulkan sure

**Comment by vkosuri** [comment]
I remember correctly all robot test values are in Unicode values, that's the reason we made it as ``` not self._is_json_data()```

It seems to me working fine with json data also

```Robot
Post Requests JSON Data
    [Tags]  post
    Create Session  httpbin  http://httpbin.org
    ${data}=  Create Dictionary  name=bulkan  surname=evcimen
    &{headers}=  Create Dictionary  Content-Type=application/json
    ${resp}=  Post Request  httpbin  /post  data=${data}  headers=${headers}
    ${output}=  To Json  ${resp.content}  pretty_print=True
    Log  ${output}
    ${result}=  To Json    ${resp.json()['data']}
    Dictionary Should Contain Value  ${result}  bulkan
    Dictionary Should Contain Value  ${result}  evcimen
```

Could you provide a simple testcase with failing scenario?

**Comment by vkosuri** [comment]
@bale836 any updates on this issue?

**Comment by bale836** [comment]
yes, @vkosuri  is right.
i check it again with original version, it is work now.
maybe i have another mistake in that test, you can close it.
