### ISSUE TITLE
execfile in the setup.py file is not available in python3 

### ISSUE THREAD

**Issue by bobdoah** [bulkan/robotframework-requests#109]
It's not possible to install the library under python3 as the execfile builtin method has been removed:

 ```bash
The command '/bin/sh -c pip install -U robotframework-requests' returned a non-zero code: 1
rowilliams@bateman:~/work/docker_playground$
rowilliams@bateman:~/work/docker_playground$ pip install -U robotframework-requests
Collecting robotframework-requests
  Downloading robotframework-requests-0.4.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-m910tj5b/robotframework-requests/setup.py", line 6, in <module>
        execfile(join(dirname(abspath(__file__)), 'src', 'RequestsLibrary', 'version.py'))
    NameError: name 'execfile' is not defined

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-m910tj5b/robotframework-requests/
```

**Comment by abhishekbth01** [comment]
Is there other way to install robotframework-ExcelLibrary?
Using cached robotframework-excellibrary-0.0.2.zip (61 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\abhishek\appdata\local\programs\python\python37-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Abhishek\\AppData\\Local\\Temp\\pip-install-uvskq9cy\\robotframework-excellibrary\\setup.py'"'"'; __file__='"'"'C:\\Users\\Abhishek\\AppData\\Local\\Temp\\pip-install-uvskq9cy\\robotframework-excellibrary\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Abhishek\AppData\Local\Temp\pip-install-uvskq9cy\robotframework-excellibrary\pip-egg-info'
         cwd: C:\Users\Abhishek\AppData\Local\Temp\pip-install-uvskq9cy\robotframework-excellibrary\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Abhishek\AppData\Local\Temp\pip-install-uvskq9cy\robotframework-excellibrary\setup.py", line 23, in <module>
        execfile(join(dirname(__file__), 'ExcelLibrary', 'version.py'))
    NameError: name 'execfile' is not defined
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by lucagiove** [comment]
Doesn't seem the right place to ask help for `robotframework-excellibrary` this is a different project.

**Comment by lucagiove** [comment]
By the way in this library execfile has been replaced with compile:

```
with open(version_file) as file:
    code = compile(file.read(), version_file, 'exec')
    exec(code)
```
