### ISSUE TITLE
Create Session keyword prints "Argument types are..." in the logs.

### ISSUE THREAD

**Issue by roimvargas** [bulkan/robotframework-requests#111]
The Create Session keyword in printing the following message to Robot logs:
```
Argument types are:
<type 'unicode'>
```

Or the below message if max_retries is passed as max_retries=${1}:
```
Argument types are:
<type 'int'>
```

This problem does not affect the test result but causes confusion, since the message appears out of context in the logs. The test developer does not know what is the message referring to.

This is happening because in the `_create_session` method of `RequestsKeywords `class, the max_retries argument is being converted to integer using another Robot keyword.
`max_retries = self.builtin.convert_to_integer(max_retries)`

In order to overcome this problem the above instruction can be replaced to use native python method int() as shown below.
`max_retries = int(max_retries)`

The int() method guarantees that, if a string is sent as parameter it is converted to integer without printing additional messages to the log.

**Comment by vkosuri** [comment]
@roimvargas the suggested PR changes are already pushed into master with latest PR, do you have any further comments on this issue?

**Comment by roimvargas** [comment]
Hi @vkosuri,
No. The issue is resolved with the PR changes.
Thank you!
