### ISSUE TITLE
Works too slow behind corporate proxy (approx. 10 times slower than httplibrary)!

### ISSUE THREAD

**Issue by Tset-Noitamotua** [bulkan/robotframework-requests#116]
Hi, I have speed / performance issues with this library when using it behind a proxy although the tests run against an internal service which does NOT require a proxy. It´s like this lib or 'request' is ignoring or takes to long to process the NO_PROXY settings.

The example test run below shows a comparison with [robotframework-httplibrary](https://github.com/peritus/robotframework-httplibrary) [1] which runs about 10 times faster.

![image](https://cloud.githubusercontent.com/assets/5635462/15888360/d6b164f6-2d66-11e6-9d45-c0a6cb97d765.png)

Cheers
Tset

[1] https://github.com/peritus/robotframework-httplibrary

**Comment by Tset-Noitamotua** [comment]
EDIT: If I turn off proxy settings in Windows then performance is approx. the same as with httplibrary. Of course that can be considert as a workaround only.

I guess that `Create Session` does not process default settings `proxies=None` correctly(?)

**Comment by Tset-Noitamotua** [comment]
It´s a known bug in 'requests' --> [#2988](https://github.com/kennethreitz/requests/issues/2988)

**Comment by Tset-Noitamotua** [comment]
I reopen this with respect to the idea represented by PR #117

This could be the easiest way to make this library usable on corporate networks which are behind a proxy but at the same time the tests do not need to go through that proxy.

Unfortunately #117  does not finally solve the delay issue. But may be some one else can pick up the idea with `trust_env` and make it working.

**Comment by Tset-Noitamotua** [comment]
Implemented [Lukasa`s](https://github.com/kennethreitz/requests/issues/2988#issuecomment-224686400) suggestion ... unfortunately still having a ~5 seconds delay

![image](https://cloud.githubusercontent.com/assets/5635462/15927749/af23e0f2-2e43-11e6-815a-bda364455f91.png)

![image](https://cloud.githubusercontent.com/assets/5635462/15927798/e9e9b77a-2e43-11e6-94b9-46c9829bca4e.png)

![image](https://cloud.githubusercontent.com/assets/5635462/15927899/604a5794-2e44-11e6-9074-180696ca7c29.png)

**Comment by Tset-Noitamotua** [comment]
> @Tset-Noitamotua And you're entirely confident that the session is being used?

May I redirect [this question](https://github.com/kennethreitz/requests/issues/2988#issuecomment-224920991) to you @bulkan ?

**Comment by vkosuri** [comment]
@Tset-Noitamotua can you try with this patch https://github.com/bulkan/robotframework-requests/pull/122? and let us know your observations?

**Comment by Tset-Noitamotua** [comment]
@vkosuri of course, will check it tomorow in office.

**Comment by vkosuri** [comment]
Thanks @Tset-Noitamotua I have added trust_env param also, you could try with this.

**Comment by Tset-Noitamotua** [comment]
It works! Thanks @vkosuri !
And I found out that my implementaion (#118), works as well :-))).
But there is one important thing to note: `False` needs to be passed in  correctly:
**IMPORTANT USE ${FALSE} -->** `trust_env=${FALSE}`. The mistake I did was I passed it in as string `trust_env=Flase`, and I did not notice it because my own logging fooled me :-/

![image](https://cloud.githubusercontent.com/assets/5635462/16558343/5c6af462-41e5-11e6-9020-7357c9b74a2a.png)

Evaluating value of `trust_env=False` reveals it was a string:
![image](https://cloud.githubusercontent.com/assets/5635462/16559128/04c40bd0-41eb-11e6-820e-795daab0ad99.png)

When setting `trust_env=${FALSE}` everything is good:
![image](https://cloud.githubusercontent.com/assets/5635462/16559180/559dee40-41eb-11e6-81a7-5967e716d3a3.png)


As addition to your PR `trust_env` should be logged properly and usage with `${FALSE}` should be mentioned in keyword documentation.

Many thanks for your support @vkosuri !

**Comment by vkosuri** [comment]
This issue has been resolved, hence closing this issue.
