### ISSUE TITLE
not an issue rather a question related to the Requests library

### ISSUE THREAD

**Issue by saurav2222** [bulkan/robotframework-requests#121]
This is not an issue rather a question related to the Requests library
Create session MD1 https://dms.md1.drivescale.com auth=${cred}
${resp}= Get request MD1 /ds/user?properties=username%2Cid
Now ${resp.json()} has the following data
[{
u 'username': u 'sk3@ds.com',
u 'id': u '08f560ec-2382-4017-94fa-507c50d705c5'
}, {
u 'username': u 'admin@ds.com',
u 'id': u '0f7f1635-844d-4c09-a4b0-905e15e74238'
}, {
u 'username': u 'ann.mccown@ds.com',
u 'id': u '224f8b7e-2dc7-4875-a99e-9aacaff6377b'
}, {
u 'username': u 'qa@ds.com',
u 'id': u '5ca6072d-2130-4e51-9325-d020ab4c3e3b'
}]

Now i need the id of the user "admin@ds.com" [or any user]
basically i have the username and i want to get the id of that username
how can i possibly get this
I am new to this so just asking a question

Thanks for your help

**Comment by vkosuri** [comment]
@saurav2222 your query should be asked in [robotframework-users](https://groups.google.com/forum/#!forum/robotframework-users).

**Comment by saurav2222** [comment]
@vkosuri   Bulkan  told me to ask this on github

**Comment by vkosuri** [comment]
Don't know it will exactly you could try like this.

``` Robot
*** Settings ***
Library     Collections

*** Testcase  ***
    ${id}=      Get Id from Response    ${resp.json()}      admin@ds.com
    

*** Keywords ***
Get Id from Response
    [Arguments]     @{response}     ${user}    
    :FOR    ${ELEMENT}    IN    @{response}
        \    Log    ${ELEMENT}
        \    ${id}=     Get From Dictionary     ${ELEMENT}      ${user}
        \    [Return]    ${id}
```

**Comment by saurav2222** [comment]
I am getting this error 
"Invalid argument specification: Positional argument after varargs."

**Comment by saurav2222** [comment]
Thank you for the help @vkosuri 
Below code works like a charm

Test1
    [Tags]    test
    ${cred}=  Create List  admin@drivescale.com  Admin11!
    Create session  MD1  https://dms.md1.drivescale.com  auth=${cred}
    ${resp}=  Get request  MD1  /ds/user?properties=username%2Cid
    ${id}=  Get User from Response  ${resp.json()}  sk3@ds.com


*** Keywords ***
Get User from Response
    [Arguments]  ${response}  ${user}

    :FOR    ${ELEMENT}    IN    @{response}
        \    Log  ${response}
        \    Log    ${ELEMENT}
        \    ${Username}=     Get From Dictionary     ${ELEMENT}      username
        \    Log    ${ELEMENT}
        \    ${id}=  Get From Dictionary  ${ELEMENT}  id
        \    log  ${id}
        \    Run Keyword if   '${user}'=='${Username}'  exit for loop
    [Return]    ${id}
