### ISSUE TITLE
How to edit a json file and replace some text in it and then use this json for a post request

### ISSUE THREAD

**Issue by saurav2222** [bulkan/robotframework-requests#123]
I have a json file in which i have replace a string and to pass to a Post Request
Below is the json file and i need to replace the value of the id with the one i have
{
    "nodeTemplates": [{
        "minDriveRpm": 5400,
        "driveTagsExcluded": null,
        "minDriveSize": 20000000000,
        "driveTagsRequired": null,
        "drives": 1,
        "name": "test",
        "rotating": true,
        "minServerCpus": 1,
        "minServerMem": 1000000000,
        "minServerBogoMips": 1000,
        "id": "83bc2007-ec69-4280-b2bc-aa51ee5db1e8",
        "serverTagsExcluded": null,
        "serverTagsRequired": null
    }],
    "name": "test"
}

How will i do that using robot framework

**Comment by bulkan** [comment]
Hi @saurav2222 

This question doesn't really relate to `robotframework-requests` and more of a general robot framework question. There is already a place to ask these questions; 

https://groups.google.com/forum/#!forum/robotframework-users

Cheers
