### ISSUE TITLE
API Rest and Robot Framework - Get Request and InsecureRequestWarning

### ISSUE THREAD

**Issue by ceol75** [bulkan/robotframework-requests#124]
Hello,
I am going to test Rest API by using 'RequestsLibrary' Robot Framework library.
I retreived correctly the token of the session.
However, I am not able to be connected without certificat. I have not certificat at my disposal.
Below the code:

 _${headers}	Create Dictionary	Accept=application/json	Authorization=token ${token_component}
Create session     session_to_component   https://${IP_component}/xxx     verify=False
${resp1}	Get Request	session_to_component	/products?includeInactive=false	headers=${headers}__

**unexpected error: C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py:821: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html InsecureRequestWarning)**

When I set ‘verify=False’ or ‘verify=True’ in 'Create session', I have the error message:

**SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)**

Have you already look at the answers there: https://github.com/bulkan/robotframework-requests/issues/5 and it does not work for me.
Thank you in advance.

**Comment by vkosuri** [comment]
@ceol75 did you tried like this?

```Robot
Create Session httpbin https://httpbin.org verify=${False}
```

**Comment by ceol75** [comment]
I solved the problem because I did not cash the right token...
Thank you for your help.

PS: I tried 'verify=${False}', 'verify=False', 'verify=${True}' or 'verify=True'. It is the same behaviour.
