### ISSUE TITLE
Delete Request does not work with ${data} attribute containing unicode characters

### ISSUE THREAD

**Issue by accesslubos** [bulkan/robotframework-requests#125]
I have following request:
```
Delete Request    alias=${alias}    uri=/myapi/test    data=${data}
```

Where ${data} is for example:
```
[{u'IsoCode': u'CNY', u'Name': u'Chinese Yuan Renminbi'}]
```

Have tried to feed Put and Delete requests with the same set of data; it worked well for Put but it didn't work well for Delete. So I had a look into code and tried to simply modify one line treating the ${data} input according to the Put request method:
```
data = self._format_data_according_to_header(session, data, headers)
```

And it worked. Not sure if this is the best fix but could you please just have a proper look into it? Thanks.

**Comment by bulkan** [comment]
Pull Requests welcome :)

**Comment by vkosuri** [comment]
This PR https://github.com/bulkan/robotframework-requests/pull/126 has been merged into master hence closing this issue.
