### ISSUE TITLE
POST request fails when both data and files are provided

### ISSUE THREAD

**Issue by volinthius** [bulkan/robotframework-requests#131]
When making a POST request with both `data` and `files` keyword arguments the request fails with:

```
$ pybot test1.txt                                                                
==============================================================================
Test1                                                                         
==============================================================================
Test One                                                              | FAIL |
ValueError: Data must not be a string.
------------------------------------------------------------------------------
Test1                                                                 | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
```

Requests Python library makes a check against `data` (when using `files`) in `requests/models.py` in function `_encode_files`:

```
if (not files):
    raise ValueError("Files must be provided.")
elif isinstance(data, basestring):
    raise ValueError("Data must not be a string.")
```

Here is test case to reproduce the error:

```
*Settings*

Library  RequestsLibrary
Library  OperatingSystem

*Test Case*
Test One
     Create Session  Foo  http://localhost
     ${data}=  Create Dictionary  foo=bar
     Create File  foobar  content=foobar
     ${files}=  Evaluate  open('foobar')
     Post Request  Foo  /foo  data=${data}  files=${files}
```

I'm using the following library versions (from `pip list`):

- requests (2.11.1)
- robotframework (3.0)
- robotframework-requests (0.4.5)

**Comment by volinthius** [comment]
I've found a workaround by using two-tuple as `data`:

```
${data}=  Evaluate  [('foo', 'bar')]
```

However the documentation states that 

> data a dictionary of key-value pairs that will be urlencoded 

.

**Comment by vkosuri** [comment]
@volinthius look into this issue, give few minutes

**Comment by vkosuri** [comment]
Looks like something went wrong, Need some more time, i am busy with other tasks, If you are interested work on this issue, please submit a pull request.

Failing testcase scenario

``` Robot
*** Settings ***
Library           RequestsLibrary
Library           OperatingSystem
Library           Collections

*** Test Case ***
Post With File
    [Tags]    post
    Create Session    httpbin    http://httpbin.org
    ${data}=    Create Dictionary    foo=bar
    ${file_data}=    Get Binary File    ${CURDIR}${/}data.json
    &{files}=    Create Dictionary    file=${file_data}
    ${resp}=    Post Request    httpbin    /post    files=${files}    data=${data}
    ${file}=    To Json    ${resp.json()['files']['file']}
    Dictionary Should Contain Key    ${file}    one
    Dictionary Should Contain Key    ${file}    two
```

**Comment by vkosuri** [comment]
Apologies, Not an real bug removing ``bug`` tag from this post.

**The Root cause** of this issue was need to add headers to request to sucessed, A similar question was posted on stackoverflow, please find it here http://stackoverflow.com/questions/27553082/valueerror-data-must-not-be-a-string

After look into this post, you have to rewrite the testcase some thing like below

```Robot
Post Request With Data and File
    [Tags]    post
    Create Session    httpbin    http://httpbin.org
    &{headers}=    Create Dictionary    Content-Type=application/octet-stream
    &{data}=    Create Dictionary    name=mallikarjunarao    surname=kosuri
    Create File    foobar.txt    content=foobar
    ${file_data}=    Get File    foobar.txt
    &{files}=    Create Dictionary    file=${file_data}
    ${resp}=    Post Request    httpbin    /post    files=${files}    data=${data}    headers=${headers}
    Should Be Equal As Strings    ${resp.status_code}    200
```

**Comment by vkosuri** [comment]
@volinthius could you try and let me know of your results?

**Comment by volinthius** [comment]
My system under test requires form submission as `multipart/form-data` using both data and files. I guess this is not currently possible?

**Comment by volinthius** [comment]
@vkosuri sure, your test case works if I use a service which understands `application/octet-stream` on form submission. But I rather use the workaround posted earlier for now.

**Comment by vkosuri** [comment]
I tried with your workaround, The sever throws 500 error. If possible could
you please let us know are there any benefit/requiremnet behind this
request?

**Comment by vkosuri** [comment]
@volinthius Seems to some restrictions with requests, a bug thread here https://github.com/kennethreitz/requests/pull/3029

Did you verified the same with requests?

**Comment by volinthius** [comment]
The test passes correctly when using Requests library directly:

```
*Settings*

Library  RequestsLibrary
Library  OperatingSystem

*Test Case*
Test One
  &{data}=  Create Dictionary  foo=bar
  Create File  foobar  content=foobarcontent
  &{files}=  Evaluate  {'foofile': open('foobar')}
  ${resp}=  Evaluate
  ...  requests.post('http://localhost:8000/foo', data=$data, files=$files)
  ...  modules=requests
  Log  ${resp}  console=${TRUE}
```

```
$ pybot test1.txt 
==============================================================================
Test1                                                                         
==============================================================================
Test One                                                              ....<Response [200]>
Test One                                                              | PASS |
------------------------------------------------------------------------------
Test1                                                                 | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
==============================================================================
```

In dummy back-end it looks like:

```
$ echo 'HTTP/1.1 200 OK' | nc -l -p 8000                                                       
POST /foo HTTP/1.1
Host: localhost:8000
Connection: keep-alive
Accept-Encoding: gzip, deflate
Accept: */*
User-Agent: python-requests/2.11.1
Content-Length: 245
Content-Type: multipart/form-data; boundary=07f07d31a10a4affa0fc2bb6e07f94e7

--07f07d31a10a4affa0fc2bb6e07f94e7
Content-Disposition: form-data; name="foo"

bar
--07f07d31a10a4affa0fc2bb6e07f94e7
Content-Disposition: form-data; name="foofile"; filename="foobar"

foobarcontent
--07f07d31a10a4affa0fc2bb6e07f94e7--
```

**Comment by vkosuri** [comment]
@volinthius thank you all your observations, I am little busy with other tasks, Pull requests are much appreciated!!

**Comment by vkosuri** [comment]
@volinthius I tried your scenario and I could able to reproduce this issue, By reading some of the [documentation ](http://docs.python-requests.org/en/latest/user/quickstart/#post-a-multipart-encoded-file) about multipart-encoded data, The workaround you specified is the correct way of sending a POST request to the unit, when you specified multipart-encoded data.

I am planning add testcase about your scenario, and also i am planning update documentation about encoding data.

@bulkan any comments/suggestions

**Comment by bulkan** [comment]
@vkosuri if you're happy I'm happy :)

**Comment by vkosuri** [comment]
Thank you @bulkan,

@volinthius any ideas or suggestions?

**Comment by vkosuri** [comment]
@volinthius do you have any final comments?

**Comment by volinthius** [comment]
@vkosuri could we pass through data when using files? I've added pull request: https://github.com/bulkan/robotframework-requests/pull/139.

**Comment by vkosuri** [comment]
@volinthius Thank you very much, Cheers :+1:

**Comment by AntonioBusillo** [comment]
Hello @bulkan and @vkosuri did you update your Library in order to use multiple files as `multipart/form-data`?

Right now I have this situation:

```
&{files}=  Evaluate  {'file1': open('file1'),'file2': open('file2')}
    ${resp}=    Evaluate
    ...  requests.post('http://IP:PORT/DIRECTORY', params=$params, files=$files)
    ...  modules=requests
```
along with the rest of the test. As @volinthius suggested in a previous post.

I would like to use as much as possible your Library.

**Comment by vkosuri** [comment]
@AntonioBusillo Yes Merged into master https://github.com/bulkan/robotframework-requests/commit/a41b600aa9fc0213e67a73c40b8245978a895678

**Comment by AntonioBusillo** [comment]
Ok it seems to work. Maybe, in the first test, I just messed up something. Thank for your help :)
