### ISSUE TITLE
Support HTTPDigest

### ISSUE THREAD

**Issue by balp** [bulkan/robotframework-requests#133]
I like to use the tests against Gerrit (from google) that uses HTTPDigest as authentications scheme. Support for that would be nice as Requests have it.

**Comment by bulkan** [comment]
@balp pull requests are welcome.

**Comment by bulkan** [comment]
@balp check out this test case https://github.com/bulkan/robotframework-requests/blob/master/tests/testcase.txt#L54

**Comment by balp** [comment]
I missed checking if anything been added after the pip release.

**Comment by vkosuri** [comment]
@balp Nothing i think so, This testcase was added long back https://github.com/bulkan/robotframework-requests/issues/74
