### ISSUE TITLE
Add doc to use GET with allow_redirects=False

### ISSUE THREAD

**Issue by kenden** [bulkan/robotframework-requests#134]
It was not easy to find who to get  allow_redirects to work.

I finally found how to use it in this PR
https://github.com/bulkan/robotframework-requests/pull/43/files 
Use: `=${false}`

```
Get Request Without Redirection
    [Tags]  get
    Create Session  httpbin  http://httpbin.org

    ${resp}=  Get  httpbin  /redirect/1  allow_redirects=${false}
    ${status}=  Convert To String  ${resp.status_code}
    Should Start With  ${status}  30
```

Having an example is the doc could be helpfull

**Comment by vkosuri** [comment]
@kenden i will update here http://bulkan.github.io/robotframework-requests/

**Comment by kenden** [comment]
Sounds good, thanks!
