### ISSUE TITLE
SSLError: hostname "xyz.com" doesn't match either of '*.abc.com' error in 0.4.5 version

### ISSUE THREAD

**Issue by chetand24** [bulkan/robotframework-requests#138]
I am getting SSLError: hostname ... doesn't match either of ... error when verify=False provided in "Create Session" keyword.

This is working perfectly in 0.3.8 version.

**Comment by vkosuri** [comment]
Thank you, could you provide a sample testcase and stack trace, of this issur, this will give an idea how to debug further

**Comment by vkosuri** [comment]
@chetand24 Any updates?

**Comment by chetand24** [comment]
This is something to do with certificate not proper or not available in server for host.

Create Session    ${SERVICE_NAME}    ${REQUEST_HOST}    verify=${verify_certificate}     auth=${auth}

If certificate is having any issue in server I provided "verify=False" which was working fine in 0.3.8 but when I switch to 0.4.5 I am getting error.

**Comment by vkosuri** [comment]
Did you verified ${verify_certificate} having ``boolean`` values?

If any issues with server with it return ${true} or ${false}?

**Comment by vkosuri** [comment]
@chetand24 any updates
