### ISSUE TITLE
`pip install` fails on python3.x

### ISSUE THREAD

**Issue by vanzaj** [bulkan/robotframework-requests#143]
create v0.4.6 and push to pypi?

**Comment by vkosuri** [comment]
@bulkan could you please create v0.4.6

**Comment by vkosuri** [comment]
@vanzaj meanwhile how about downloading master?

**Comment by vanzaj** [comment]
@vkosuri, it works fine with a local installation. Is there any reason why current master is not published on pypi? Without it I'd need two different CI configs for py2 and py3.

**Comment by bulkan** [comment]
https://pypi.python.org/pypi/robotframework-requests/0.4.6

**Comment by vkosuri** [comment]
@bulkan Thanks
