### ISSUE TITLE
How may I testing the length of resp?

### ISSUE THREAD

**Issue by liweijian** [bulkan/robotframework-requests#149]
According to the [official document](http://bulkan.github.io/robotframework-requests/), we can get the kv json pair by `${resp.json()}` , or we can get the response code by `${resp.status_code}`.

I was wondering if maybe we could get the length of resp? In some case, the response has no body(The length of body is zero), and there will be errors if we `${resp.json()}` on that response.

**Comment by vkosuri** [comment]
Try and let me know

``` Robotframework
{$resp.headers['content-length']}
```

**Comment by liweijian** [comment]
Works well, great thanks
