### ISSUE TITLE
Post with data but display as '<empty>'  in the log file

### ISSUE THREAD

**Issue by SylviaLan** [bulkan/robotframework-requests#155]
There are many new users meet this trouble, actually they write the data arg in the Post Request but they see this in the log file :

> 20170325 22:41:11.193 :  INFO : Post Request using : alias=api, uri=/post, data=<empty>, headers=None, files=None, allow_redirects=True 

They are often wondering whether the data value posted with the request correctly or not. This doubt comes more strongly when the sever gives an error response.

I've read the source code, only when headers is not None and 'Content-Type' in headers, data value can be logged correctly. But I get use to putting headers in  Create Session keyword, and in that case, I must write an extra row to log my data value, or else difficult to debug.

Hope a more ideal solution.

**Comment by vkosuri** [comment]
Thanks, will dig this issue

**Comment by juri33** [comment]
+1, took me a while to understand that

**Comment by qitaos** [comment]
In function  **_format_data_to_log_string_according_to_header**  in RequestsKeywords.py. 
format data to log but some conditions the data lost.

**Comment by matt-watson90** [comment]
Was the fix for this issue ever merged in? I've just come across the same issue.

**Comment by vkosuri** [comment]
@matt-watson90 I think so, If not post your example testcase and with error info

**Comment by matt-watson90** [comment]
@vkosuri when I get a chance later today I'll try and pull together a minimal example.

**Comment by odonnell-anthony** [comment]
Did this get fixed? doesn't seem so...

**Comment by Wolfe1** [comment]
One of the users of our framework noticed this error today so I believe it is still an issue.
