### ISSUE TITLE
Is it possible to test SOAP based webservices with this library?

### ISSUE THREAD

**Issue by Tset-Noitamotua** [bulkan/robotframework-requests#156]
I wonder if it is possible to test SOAP based webservices with this lib. 

I am going to dig into that but maybe somebody has already done it?

So far I've found this:

http://stackoverflow.com/questions/18175489/python-soap-using-requests#
https://gist.github.com/toast38coza/17e2ad6c2cfa2e96b0b1

**Comment by vkosuri** [comment]
@Tset-Noitamotua It would be possible if SOAP requests are in Json format. If it is XML then some of requests procedures are needs to rewrite to handle XML responses.

**Comment by vkosuri** [comment]
@Tset-Noitamotua I am closing this issue, please feel free to reopen if you have further updates
