### ISSUE TITLE
Reusing a session fails

### ISSUE THREAD

**Issue by mvh77** [bulkan/robotframework-requests#159]
Hi,

Is it normal that a session cannot be reused, say with two consecutive POST requests? I get a `ValueError: Invalid file object: <_socket._socketobject object at 0x3>` with test cases like the following that have multiple requests using the same session alias:
```
*** Settings ***
#
Library    Collections
Library    OperatingSystem
Library    RequestsLibrary

*** Test Cases ***
Post Requests
    [Tags]  post
    Create Session  httpbin  http://httpbin.org
    &{data}=  Create Dictionary  name=bulkan  surname=evcimen
    &{headers}=  Create Dictionary  Content-Type=application/x-www-form-urlencoded
    ${resp}=  Post Request  httpbin  /post  data=${data}  headers=${headers}
    ${resp}=  Post Request  httpbin  /post  data=${data}  headers=${headers}
    Dictionary Should Contain Value  ${resp.json()['form']}  bulkan
    Dictionary Should Contain Value  ${resp.json()['form']}  evcimen
```
If this is normal maybe some documentation could be added on how to manage session in test cases. Thanks!

PS: I'm on Jython in case that makes a difference.

**Comment by vkosuri** [comment]
@mvh77 I am not sure will this work on Jython, I will try to install on Jython on my machine, let you about changes https://wiki.python.org/jython/InstallationInstructions

**Comment by mvh77** [comment]
It works fine without the second call, and it works if I create a second session with a different name for the second call.

**Comment by vkosuri** [comment]
Are you trying creating two sessions in single testcase? or in different approach, if possible could you share test code?

**Comment by mvh77** [comment]
I need to do a PUT, a POST and a GET in the same test to the same server. Do I need 3 sessions? That's how I have it now but it seems stupid. Isn't CreateSession just an alias? It's not very well documented how it should be used. Should the example I gave you with two POSTs work or not?

**Comment by vkosuri** [comment]
Not required. Will update documentation about this issue
