### ISSUE TITLE
Cannot send delete request without data content

### ISSUE THREAD

**Issue by jvaa** [bulkan/robotframework-requests#160]
Since version 0.4.6 it seems to be impossible to send delete request without any data content. Some services do not accept content in delete requests and requests will fail. I have tried many ways to set data=None but always some content is sent. In delete request, default data should be None.

**Comment by vkosuri** [comment]
@jvaa Is it possible share testcase sample with stack trace?

**Comment by jvaa** [comment]
This is only what I can share right now:

${url}=    ...
Create Session    DeleteCall    ${url}    debug=10
${header}=    Create Dictionary    Content-Type=application/json
${resp}=    Delete Request    DeleteCall    /some/path    headers=${header}


<msg timestamp="20170524 10:49:07.723" level="DEBUG">Starting new HTTPS connection (1): example.org</msg>
<msg timestamp="20170524 10:49:07.737" level="DEBUG">https://example.org:443 "DELETE some/path HTTP/1.1" 400 226</msg>
<msg timestamp="20170524 10:49:07.746" level="DEBUG">send: DELETE some/path HTTP/1.1
Host: example.org
Connection: keep-alive
Accept-Encoding: gzip, deflate
Accept: */*
User-Agent: python-requests/2.14.2
Content-Type: application/json
Content-Length: 2
[]
reply: HTTP/1.1 400 Bad Request

**Comment by ombre42** [comment]
No content is sent if you do not send the Content-Type header, which you should not be sending anyways if you are not sending content, right?

**Comment by jvaa** [comment]
Nice catch. Service example contained that content type which is why we sent it, but it seems to work without it. However I think content should not be sent if it is not set, but this workaround is good enough.
