### ISSUE TITLE
Default debug level based on Robot's log level

### ISSUE THREAD

**Issue by ombre42** [bulkan/robotframework-requests#172]
Enhancement request:
Instead of defaulting the debug level in `Create * Session` keywords to 0, select an appropriate level based on Robot's log level.

This is what we do:
```
    ${debug_level}    Evaluate    {'TRACE': 2, 'DEBUG': 1}.get($LOG_LEVEL, 0)
    Create Session    session_name    some_url    debug=${debug_level}
```

But it would be nice if this was automatic. Other libraries, such as Selenium2Library, log a lot more based on the Robot log level without any other changes.

One downside is that user's logs could grow much larger just by updating RequestsLibrary if this is implemented.

Would be happy to do a PR for this. I don't really know if debuglevel > 1 ever makes a difference. Seems like its really on or off.

**Comment by vkosuri** [comment]
Thanks @ombre42 Looking for a PR

**Comment by vkosuri** [comment]
@ombre42 any update about this issue?

**Comment by vkosuri** [comment]
@ombre42 I am closing this PR, Please fell free to reopen if you have any further updates on this issue.
