### ISSUE TITLE
Client certificates

### ISSUE THREAD

**Issue by neilblue** [bulkan/robotframework-requests#173]
Hello,
is it possible to provide a client certificate and key. With curl I would do it like this:

curl -i -k --key CERT.key --cert CERT.pem -H 'Content-Type:application/json' --data @data.txt https://server:8443/path

Thanks

**Comment by vkosuri** [comment]
Here is an example
```Robotframework
Get HTTPS & Verify Cert with a CA bundle
    [Tags]  get
    Create Session    httpbin    https://httpbin.org   verify=${CURDIR}${/}cacert.pem
    ${resp}=  Get Request  httpbin  /get
    Should Be Equal As Strings ${resp.status_code} 200
```

**Comment by neilblue** [comment]
Thank you,

I have tried this and when I use a combined (cert/key) pem file, I receive a handshake_failure in this case. However the same pem file works successfully with curl.

**Comment by neilblue** [comment]
I have been playing with the Certificate class and I can get client TLS to work witih a change like this. I am trying to get the rest of the framework to accept this properly at the moment.

	public KeyStore createCustomKeyStore(String path, String password) {
		KeyStore trustStore;
		try {		    
            if (password!=null && path.endsWith(".jks")) {
                trustStore = KeyStore.getInstance("JKS");
                trustStore.load(new FileInputStream(path), password.toCharArray());
            } else {
                trustStore = KeyStore.getInstance(KeyStore.getDefaultType());
                trustStore.load(null);
                int i = 0;
                for (X509Certificate cert : this.getCertificatesFromFile(path)) {
                    trustStore.setCertificateEntry("Custom_entry_" + i, cert);
                    i++;
                }
                logger.debug("Certificates in trustStore: " + (i));
            }
			return trustStore;
		} catch (KeyStoreException e) {
			throw new RuntimeException(String.format("%s occurred. Error message: %s", e.getClass(), e.getMessage()));
		} catch (NoSuchAlgorithmException e) {
			throw new RuntimeException(String.format("%s occurred. Error message: %s", e.getClass(), e.getMessage()));
		} catch (CertificateException e) {
			throw new RuntimeException(String.format("%s occurred. Error message: %s", e.getClass(), e.getMessage()));
		} catch (IOException e) {
			throw new RuntimeException(String.format("%s occurred. Error message: %s", e.getClass(), e.getMessage()));
		} 

	}

**Comment by vkosuri** [comment]
@neilblue I think you are trying explain your usecase using java ap?, robotframework-requests are based on python [requests](https://github.com/requests/requests)

Could you please try below snippet with your key, if you get any error please traces to debug further.

``` Python
url='http://httpbin.org'
cafile = 'cacert.pem' # http://curl.haxx.se/ca/cacert.pem
r = requests.get(url, verify=cafile)
```

**Comment by neilblue** [comment]
Hi vkosuri, the ca test cases work fine. The problem is that client TLS authentication does not seem to be supported in the library now. The change I posted is and update to com.github.hi_fi.httpclient.security.Certificate to support client authentication in HttpClient.

**Comment by vkosuri** [comment]
Hi @neilblue Yes i think you were right, If possible could you please submit a PR

before you trying could you please try below snippet and let me know your inputs.

More information how to use cert available here http://docs.python-requests.org/en/master/api/?highlight=tls%20authentication#requests.request

``` Python
url='http://httpbin.org'
r = requests.get(url, cert=(cert,key),verify=True)
```

**Comment by vkosuri** [comment]
@neilblue I missed track of this issue, is there any update on this issue?

**Comment by neilblue** [comment]
I am pretty busy, but I am tying to put together a PR for this. It will require changed to httpclient as well as the library.

**Comment by neilblue** [comment]
I have created a branch with the updated but I don't have access to push
the branch.

**Comment by vkosuri** [comment]
I think this documentation will help https://help.github.com/articles/about-pull-requests/

**Comment by elskohder** [comment]
Hi @neilblue @vkosuri, 

I have submitted a PR (https://github.com/bulkan/robotframework-requests/pull/171) for using client-side certificates for the Python-based RBF. Maybe this will help in your efforts.

~ Andrew

**Comment by neilblue** [comment]
Thank you Andrew,

That will be useful. My main problem ATM is lack of time :) I will get
back to this when some of the dust settles.

Thanks,

Neil

**Comment by vkosuri** [comment]
@neilblue do have any comments on #171

**Comment by vkosuri** [comment]
@neilblue I am closing this issue #171 merged into master, Please feel free to reopen if you any questions or any concerns.
