### ISSUE TITLE
Create Session - max_tries failing with TypeError

### ISSUE THREAD

**Issue by nkadioglu** [bulkan/robotframework-requests#174]
Hi,

Using v0.4.7, and not specifying a max_tries in Create Session, I am getting the following error:

"TypeError: unsupported operand type(s) for -=: 'Retry' and 'int"

Is this a bug?

**Comment by vkosuri** [comment]
@nkadioglu Did you tried with float values instead of integer?

**Comment by vkosuri** [comment]
@nkadioglu any update about this issue?

**Comment by nkadioglu** [comment]
I was not specifying a value @vkosuri but the issue is resolved - there was a mismatch between robot framework and the requests library. Thank you!

**Comment by vkosuri** [comment]
Thanks @nkadioglu please feel free to reopen this issue, if you have anything.

**Comment by rbgarga** [comment]
@nkadioglu I'm facing the same issue here. Do you remember any detail about the fix?

**Comment by nkadioglu** [comment]
@rbgarga mismatch between robot framework and the requests library versions.
