### ISSUE TITLE
Flag allow_redirects ignored

### ISSUE THREAD

**Issue by sebastian-garn** [bulkan/robotframework-requests#175]
Hi,

I tried to disable automatic redirect but for some reason the flag is ignored:

```
Create Session | test | http://google.com
${res}= | Get Request | test | uri=/ | allow_redirects=False
Log | Status Code: ${res.status_code} History: ${res.history} | level=warn
```

I would expect as a status_code either 301 or 302 but its 200:
[ WARN ] Status Code: 200 History: [<Response [302]>]

I'm using the latest version of robotframework-requests (0.4.7).

**Comment by vkosuri** [comment]
@sebastian-garn could you please share http headers?

**Comment by vkosuri** [comment]
Replace ``False`` with ``${False}`` It will work

```Robotframework
*** Settings ***
Library 	Collections
Library 	RequestsLibrary

*** Test Cases ***
Allo Redirects
    Create Session  test  http://google.com
    ${res}=  Get Request  test  uri=/  allow_redirects=${False}
    Log  Status Code: ${res.status_code} History: ${res.history}  level=warn
```

**Comment by vkosuri** [comment]
@sebastian-garn I am closing this issue with proposal changes in your script, feel free to reopen if your problem didn't resolved.

**Comment by sebastian-garn** [comment]
It works. Thanks. Might have been helpful to have at least an example in the documentation about that ;)

**Comment by vkosuri** [comment]
Will do
