### ISSUE TITLE
Explicit headers have lower priority than session headers

### ISSUE THREAD

**Issue by NickOnuchin** [bulkan/robotframework-requests#180]
Could you change the logic of headers merge in RequestsKeywords.py (in def _merge_headers(session, headers))?

If headers is set explicit for some request it's ignored (overlapped) in case we have the same session header.
I set session headers for my usual requests but some requests need in changed headers. 
It would be good if explicit headers have priority over session headers.

**Comment by vkosuri** [comment]
@NickOnuchin apologies for delay response, please feel free to submit a PR to improve the code base.

**Comment by bulkan** [comment]
Closing as there wasn't updates
