### ISSUE TITLE
disable_warnings disables all robot info, warn, debug messages

### ISSUE THREAD

**Issue by StefanIGit** [bulkan/robotframework-requests#182]
Hi,
When I create a session like
`Create Session	somename    https://${IP}:${PORT}	auth=${auth}	disable_warnings=1`

it kills globally all robot info, warn, debug messages.
Only Error level is show.

I tried to suppress this with it and it work but with the above side effect:

`unexpected error: C:\Python27\lib\site-packages\urllib3\connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
C:\Python27\lib\site-packages\urllib3\connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)`

After some digging I figured out only this is what I need for that
`requests.packages.urllib3.disable_warnings()`

But this is only active if disable_warnings is True and verify is False.

I'm not sure what other kinds of warnings should be disabled by this ... override?
`            logging.basicConfig() # you need to initialize logging, otherwise you will not see anything from requests
            logging.getLogger().setLevel(logging.ERROR)
            requests_log = logging.getLogger("requests")
            requests_log.setLevel(logging.ERROR)`

But the Help, for me,  is miss leading
`        disable_warnings Disable requests warning useful when you have large number of testcases                
`

**Comment by vkosuri** [comment]
@StefanIGit Thanks for looking into this, could you please submit a pull request with proposed changes?

**Comment by StefanIGit** [comment]
The thing is I'm not sure if the that is/was the idea behind the "disable_warnings" option.
My expectation for an option like this in a robot library is, disable warnings of that library only (including all imported libraries like here urllib I think)

Here's the pull request [https://github.com/bulkan/robotframework-requests/pull/183](url)

I have not enough experience  with requests / REST APIs so I cannot tell if this is a bad way, but if works for the default verify=False which seems to me like "I do not care about the cert, go away" so this warning should not be displayed.

**Comment by StefanIGit** [comment]
For the "kill all robot logger settings" thing, I did some research and this is what I came up with.
It adds the logging library to a class but does not dictate the way of logging.
Basically it adds by default a /dev/null logger and if the user of a script wants logging she/he can 
configure the logging library and be happy.
and it shows how to silence a logger, useful for paramiko :)

`### LoggingInClastTest.py ###
import logging

class myclass():
    '''
    Awesome example how to use logging is a library
    '''

    def __init__(self):
        '''
        So the init here it will be execute when a new instance is created like
        thing = myclass()
        '''
        # give Logger a nice name so you know where the logoutput comes from in logfile and mayby disable it, like paramiko
        #self.logger = logging.getLogger(__name__) # use name on file 
        # or set manually
        self.logger = logging.getLogger('NameOfmyClass')
        
        # If you have more that one file in your package e.g. testApi.sshShell.py        
        # then you could name your logger this way, so all loggers are grouped so you can
        # config / set log level for the complete package with one line see # make logger "NameOfmyClass" silent
        # self.logger = logging.getLogger('NameOfmyClass.sub name'+__name__) 
        
        # add "log to  /dev/null" if the main program does not use logging
        self.logger.addHandler(logging.NullHandler())
        # this is how the logger is used in the class
        self.logger.info('Ole ole it looks almost working :D')
        
    def dostuff(self):
        '''
        a function of the class it can / should be called by the main script...
        '''
        self._insideJob()
        self.logger.error('This should nerver happen... Mariia did something')
        self.logger.debug('What the F... is goning on here?')
        self.logger.critical('oO we will all DIE!!!!!11!1 no more candy')

    def _insideJob(self):
        '''
        this function should not be called from outside of the class
        
        '''
        self.logger.warn('This can happen but.... who cares :)')



### someScript.py ### using the LoggingInClastTest lib

# Using the class without logging

import LoggingInClastTest
print 'Start no logging'
thing = LoggingInClastTest.myclass()
thing.dostuff()
print 'End no logging'


# Using the class with logging
import logging

logging.basicConfig(level=logging.DEBUG,
                    format='%(asctime)s %(name)-20s %(levelname)-8s %(message)s',
                    datefmt='%Y-%m-%d %H:%M:%S')

logging.info('Start with logging')
newthing = LoggingInClastTest.myclass()

newthing.dostuff()

# make logger "NameOfmyClass" silent
# this makes all logger starting with "NameOfmyClass.XXXXX" silent
logging.getLogger("NameOfmyClass").setLevel(logging.CRITICAL)
logging.info('Start with only crit class logging')
`

**Comment by StefanIGit** [comment]
Hmm but I'm not sure how to apply it to this lib, it uses a lot of logging ways.
I did not yet fully understand the python logging library and the robot logger.

RequestsKeywords.py line 94, I know where this comes from
 `        self.builtin.log('Creating session: %s' % alias, 'DEBUG')
`
line 183 from robot.api import logger
```python
        logger.info('Creating Session using : alias=%s, url=%s, headers=%s, \
                    cookies=%s, auth=%s, timeout=%s, proxies=%s, verify=%s, \
                    debug=%s ' % (alias, url, headers, cookies, auth, timeout,
                                  proxies, verify, debug))
```

line 115... the part I do not understand, I can just remove the 2 logging lines and disable_warnings=True
works as expected, it disables the self signed cert warnings but I still get warn and debug from my custom libs.
But why?
```python
        if disable_warnings:
            #logging.basicConfig() # you need to initialize logging, otherwise you will not see anything from requests
            #logging.getLogger().setLevel(logging.ERROR)
            requests_log = logging.getLogger("requests")
            requests_log.setLevel(logging.ERROR)
            requests_log.propagate = True
```

**Comment by bulkan** [comment]
Closed as there wasn't any further updates
