### ISSUE TITLE
Getting response headers from the http request

### ISSUE THREAD

**Issue by wolfebrian2120** [bulkan/robotframework-requests#187]
When we submit our get request a cookie gets set in the response header. We would like to be able to get that cookie for another http request. using ${resp.json} just returns the json of the body of the response and when I log ${resp} it just prints the http response code i.e. 200. Does current functionality allow the retrieval of the response headers?

**Comment by wolfebrian2120** [comment]
Hi thanks for the hard work on this project. We realized that the create session maintains the cookie info.

**Comment by vkosuri** [comment]
@wolfebrian2120 Thank you very much.
