### ISSUE TITLE
Request: Support for bare CONNECT request

### ISSUE THREAD

**Issue by akoolenbourke** [bulkan/robotframework-requests#188]
Hi there.

I'd like to be able to perform a CONNECT request without having to couple that to a regular request. This is so I can use the library to test my proxy server handling of CONNECT by itself.

This would also require being able to retrieve the response as well and irrespective of whether the url was HTTPS or HTTP.

Thanks.

**Comment by vkosuri** [comment]
@akoolenbourke could you please submit a PR for this feature request?

**Comment by akoolenbourke** [comment]
Excuse my ignorance, but do you want me to implement a fix and perform a PR? If so, unfortunately I don't know python and am bogged down with other work. I'll try and get to it at some point.
Thanks

**Comment by bulkan** [comment]
Closed as there wasn't any further updates
