### ISSUE TITLE
Request to update PIP repository with latest

### ISSUE THREAD

**Issue by sudhagarc** [bulkan/robotframework-requests#189]
I'm wondering if it would be possible to update the PIP repository with latest package. The current version in PIP is 0.4.7, which is 8 months old. I notice quite a few nice changes that went in after that, especially in the areas of SSL, certificate verification, etc.

Thank you.

**Comment by trogdor259** [comment]
I am creating a Docker image to run my tests and I'd really rather use the pip install to get the newest version rather than cloning the repo and installing the newest changes.

**Comment by bulkan** [comment]
https://pypi.org/project/robotframework-requests/0.5.0/
