### ISSUE TITLE
Passphrase using the method "Client Cert Session"

### ISSUE THREAD

**Issue by jjsa01** [bulkan/robotframework-requests#190]
I have a question about the following request:

```
Custom API
@{client_certs}    Create List     ${CURDIR}${CERTIFICATE_PATH}&{CERTIFICATE}    ${CURDIR}${CERTIFICATE_PATH}&{KEY}
Create Client Cert Session  crtsession  ${SERVER}   client_certs=@{client_certs}
${resp}    Get Request     crtsession  /values 
Should Be Equal As Strings  ${resp.status_code}     200
```

The console waits for someone type the passphrase.
I want to automate this because I have more requests to be exact 42 requests that use this kind of certificates.
There is some way to automate that?

**Comment by bulkan** [comment]
Closing due to no further updates
