### ISSUE TITLE
browser testing with Certficate

### ISSUE THREAD

**Issue by aawoke** [bulkan/robotframework-requests#191]
I am trying to automate web browser testing in RF in Linux environment.   Our application requires to have a certificate to a given user.  (in other words, if i want to access our apps via the browser, I have imported the certificate to my browser and get into it that way.)    

Question I have is how can i automate that in RF once i open the browser.  I have read somewhere saying create firefox profile and that didn't work.  Any help is much appreciated.

**Comment by bulkan** [comment]
Closing as there wasn't updates
