### ISSUE TITLE
Allow different values for Content-Disposition name and filename

### ISSUE THREAD

**Issue by teelicht** [bulkan/robotframework-requests#195]
When creating a post request with an attached file (multipart/form-data), the Content-Disposition block within the boundary looks as follows: `Content-Disposition: form-data; name="file"; filename="file"`

Unfortunately, the 3rd-party API I'm using here needs the value in _filename_ to contain a file extension (e.g. file.xml) while not adding the extension to the value in _name_. Desired output would be: `Content-Disposition: form-data; name="file"; filename="foobar.xml"` I could not find a way to differentiate these two values in the current version of the RequestsLibrary.

**Comment by vkosuri** [comment]
@teelicht Thank you, Could you please create pull request to address this issue?

**Comment by teelicht** [comment]
@vkosuri I looked through the code but as this is the first time I remotely work with python, I'm a bit lost. However, I succeeded by directly implementing the request in python using the requests library and running it from robot:

```
import requests
def post_results():

	url = "https://foo.bar/rest/raven/1.0/import/execution/robot"
	
	querystring = {"projectKey":"KEY"}
	files = {'file': open('PATH_TO_MY_FILE\\output.xml', 'rb')}	
	headers = {
	    'Authorization': "Basic FOOBAR",
	    'Cache-Control': "no-cache"
	    }
	
	response = requests.request("POST", url, files=files, headers=headers, params=querystring, verify=False)
	
	return response
```

Probably within def post_request, the passed files information needs to be extended.

**Comment by bulkan** [comment]
Closing due to no further updates
