### ISSUE TITLE
SeleniumLibrary

### ISSUE THREAD

**Issue by dtnhoang** [bulkan/robotframework-requests#197]
Hi, thanks for providing this.  I'm wondering if there is a way to create the session and then utilize that with "Open Web Browser" with the SeleniumLibrary?  I'm having an issue with Selenium where it doesn't send the basic authentication (even when sending http://user:pass@url).  Your library does send the credentials, but I'm unable to utilize the Selenium Library browser keywords with the same requests.

**Comment by bulkan** [comment]
I don't believe this is possible
