### ISSUE TITLE
Can we have a keyword to get specific value from the json response received as we had in HttpLibrary.HTTP 

### ISSUE THREAD

**Issue by Karthik1384** [bulkan/robotframework-requests#201]
Can we have a keyword to get specific value from the json response received as we had in HttpLibrary.HTTP 

Please let me know if their is an option already available.

Sample:
How we do this using HttpLibrary.HTTP 
Note: it seems HttpLibrary.HTTP  is not active for past 6 years
${result}= | Get Json Value | {"foo": {"bar": [1,2,3]}} | /foo/bar

How we do this in POSTMAN
var jsonData = JSON.parse(responseBody);
pm.globals.set("DynaminEndpoint", jsonData.Device.id);

**Comment by trogdor259** [comment]
Why not just use `${results} | Set Variable | ${resp["foo"]["bar"]}`? That would set the value of ${results} to be the value of foo.bar.

**Comment by Karthik1384** [comment]
Thank you ... Am closing this Issue
Will be helpful if you can suggest some learning point where i can refer these type of examples
