### ISSUE TITLE
issue with certificate files to connect on a server

### ISSUE THREAD

**Issue by astrowalker2013** [bulkan/robotframework-requests#203]
`${resp}  Create Session  rigel   https://${host}    verify=${CURDIR}${/}certif.pem`
  ${resp1}  Get Request	rigel    mediacentric/`

The certificate was generated with this command :
openssl pkcs12 -in certif.p12  -passin pass:<password> -clcerts -out certif.pem

In the Report it's write 
SSLError: HTTPSConnectionPool(host='${host}', port=443): Max retries exceeded with url: /toto/ (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),)

when I used curl command i used  -k option in order to don't check the validity of the certificate.

how to do that with requestlibrary in robotframework ?
Is it possible to verify the validity of the certificate ? in this case how to do that ?
Or if is not possible is it possible to execute that by other way like by change the Library

Thanks in Advence.

**Comment by bulkan** [comment]
Closing due to no further updates
