### ISSUE TITLE
get with spaces in url in linux generate Bad Request

### ISSUE THREAD

**Issue by estivalet** [bulkan/robotframework-requests#205]
I have the following GET rest call 

Get Request     consulta    xxx/advogados/PA/NAME%20WITH%20SPACES/0

When I run this kind of GET call in a Linux (CentOS) environment I get a Bad Request 

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"><html><head><title>400 Bad Request</title></head><body><h1>Bad Request</h1><p>Your browser sent a request that this server could not understand.<br /></p></body></html>
```

Running the same call in Windows it works as expected.

I'm using Python 3.7.

Any tip?

**Comment by bulkan** [comment]
Closing due to no further updates
