### ISSUE TITLE
Pip Install does not down load 4.8 version

### ISSUE THREAD

**Issue by bejoyjohn** [bulkan/robotframework-requests#206]
Hi I am trying to down load the 4.8 version using Pip. For what ever reason I can not get past 4.7. And 4.7 does not work with json data format.

Temporarily I was able to work around copying those files to Site requirements. However can you please suggest how can I get those files.

**Comment by vkosuri** [comment]
Need to publish 0.4.8, it has only https://pypi.org/project/robotframework-requests/

**Comment by bulkan** [comment]
I published 0.5.0 now
