### ISSUE TITLE
Support parallel execute suites?

### ISSUE THREAD

**Issue by Huanxin-leolil** [bulkan/robotframework-requests#210]
All interface calls share a session, which is the session generated by the **[Create Session]** function. 

On this basic, we want to do concurrency, using **pabot**, that is, the robot framework-pabot library, so the way we want to use is: all multi-threads share a session for concurrency, so the [Create Session] function is currently called only once, and then all threads share the session.

The session can be retrieved from multithreads in my test , but when the interface is invoked, it is found that other thread interface requests fail：

error messages:

```
KEYWORD RequestsLibrary . Get Request ${agent.session}, ${uri}, headers=${header}, timeout=${timeout}
Documentation:	
Send a GET request on the session object found using the

Start / End / Elapsed:	20181109 15:06:36.520 / 20181109 15:06:36.523 / 00:00:00.003
15:06:36.523	FAIL	Non-existing index or alias 'adminsession'.
```

So I would like to ask if we support concurrent scenarios?

**Comment by Huanxin-leolil** [comment]
Read the source code of [Create Session] and find ConnectionCache  class, annotation description support multi thread concurrency.

![image](https://user-images.githubusercontent.com/12948382/48249712-e9ff7500-e436-11e8-93e9-ea2b312bfa9b.png)

![image](https://user-images.githubusercontent.com/12948382/48249776-0a2f3400-e437-11e8-8e07-8cc7a8eb36ec.png)

**Comment by Huanxin-leolil** [comment]
@vkosuri  I submitted a code using request and pabot : [https://github.com/Huanxin-leolil/request_pabot](url)
when I execute  `pabot.bat --pabotlib --processes 2 C:\Users\leo\git\request_pabot`

One of the threads failed to execute,
ERROR MESSAGE: `Non-existing index or alias 'github'.`

![image](https://user-images.githubusercontent.com/12948382/48309240-679ac080-e5b0-11e8-964c-98a72cd09d0c.png)

![image](https://user-images.githubusercontent.com/12948382/48309255-c829fd80-e5b0-11e8-9821-0645b6c70877.png)

**Comment by vkosuri** [comment]
Your testcase is wrong try below test case, you have to define an alias

```robotframework
Get Requests
    [Tags]  get    skip
    Create Session  google  http://www.google.com
    Create Session  github  https://api.github.com   verify=${CURDIR}${/}cacert.pem
    ${resp}=  Get Request  google  /
    Should Be Equal As Strings  ${resp.status_code}  200
    ${resp}=  Get Request  github  /users/bulkan
    Should Be Equal As Strings  ${resp.status_code}  200
    Dictionary Should Contain Value ${resp.json()} Bulkan Evcimen
```

**Comment by Huanxin-leolil** [comment]
@vkosuri My testcase is correct , The alias at the test case refers to variables -> ${session} 
`${resp}=	Get Request	${session}	/`
The definition of alias is at **[Suite Setup]**, You can run my example

My project runs in a way that only one alias is generated at **[Suite Setup]**, and then all threads share this alias, the problem is that when other threads use the same alias, there will be an error.

ERROR MESSAGE: `Non-existing index or alias 'github'.`

You can execute `pabot.bat --pabotlib --processes 2 C:\Users\leo\git\request_pabot` command, and try it

![image](https://user-images.githubusercontent.com/12948382/48312850-c2074180-e5ef-11e8-9161-1af62b6ac7cd.png)

![image](https://user-images.githubusercontent.com/12948382/48312852-ce8b9a00-e5ef-11e8-9af0-066ee1a38f4f.png)

**Comment by Huanxin-leolil** [comment]
Thanks! If the way of sharing session with multiple threads is supported, I think he must be a great achievement. And look forward very much !!!  @vkosuri

**Comment by lucagiove** [comment]
@Huanxin-leolil why do you matter about having the session created only once?
Pabot spawn different processes that cannot share anything directly, so what you need is to create one session for each process but basically what you want to do is just to add everything needed for your tests in a Setup Suite or Setup Test.
So that session is always available from every process and it's shared in a way that has the same configurations but is not exactly the same instance. Hope that helps.
