### ISSUE TITLE
Is there a way to log request and response?

### ISSUE THREAD

**Issue by ppazos** [bulkan/robotframework-requests#222]
I need to check requests and responses but not sure how can I log them.

**Comment by vkosuri** [comment]
I think the debug option will enable this feature. You have to pass this param while creating a session.

**Comment by lucagiove** [comment]
some further data are logged increasing log level on robot with --loglevel trace

**Comment by ppazos** [comment]
tried the debug=1, doesn't show anything extra in the log

**Comment by ppazos** [comment]
I used this keyword to increase the log level Set Log Level   trace

Still can't see request or response content. I need to debug some requests because I receive 400 responses but can't check why.

**Comment by lucagiove** [comment]
> tried the debug=1, doesn't show anything extra in the log

you've to verify in the log html not in the console

**Comment by ppazos** [comment]
thanks, I was able to get the needed data from:

Log To Console   ${resp.request.headers}
Log To Console   ${resp.request.body}

**Comment by barisekici001** [comment]
well, how to get request ep? @ppazos

**Comment by lucagiove** [comment]
just open the HTML log :) already in info mode (if you have 0.7 version) you'll see the request/response, it might be truncated change loglevel to debug if you want the complete body
