### ISSUE TITLE
Applying urlencode in params

### ISSUE THREAD

**Issue by extr3mal** [bulkan/robotframework-requests#223]
Right now i have a get call that uses user email as a parameter. 
what i have : 
https://endpoint.url/api/v1/get_request/?email=someuser@somehost.com
what i need 
https://endpoint.url/api/v1/get_request/?email=someuser%40somehost.com

The question is how to pass user's email and encode it to url ?

**Comment by virpara** [comment]
It does not work when you pass dictionary `{"email": "someuser@host.com" }` to the `params` argument to `Get Request` keyword ?

I think it will URL encode the params since they are appended to the request URL.

**Comment by lucagiove** [comment]
it should work like virpara said, but you've to pass the parameters as dictionary in "params":

            params=self._utf8_urlencode(kwargs.pop('params', None)),
