### ISSUE TITLE
Release 0.6.2 not available via pip

### ISSUE THREAD

**Issue by ppodgorsek** [bulkan/robotframework-requests#243]
Only versions up to 0.5.0 are available in pip, it would be good to release the latest one there too.

**Comment by lucagiove** [comment]
Have you tried the 0.6.2? What do you think?
Have you had any issue?

**Comment by ppodgorsek** [comment]
This is what I get in my logs when running `pip3 install robotframework-requests==0.6.2`:

> Collecting robotframework-requests==0.6.2
> ERROR: Could not find a version that satisfies the requirement robotframework-requests==0.6.2 (from versions: 0.1, 0.2.dev0, 0.2, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.3, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.4.0, 0.4.1, 0.4.2, 0.4.4, 0.4.5, 0.4.6, 0.4.7, 0.5.0)
> ERROR: No matching distribution found for robotframework-requests==0.6.2

The latest version available on [pypi](https://pypi.org/project/robotframework-requests/) is 0.5.0.

**Comment by lucagiove** [comment]
Ah yes it's not published yet I thought you cloned the repo and manually
installed the lib

Il gio 10 ott 2019, 13:09 Paul Podgorsek <notifications@github.com> ha
scritto:

**Comment by lucagiove** [comment]
@bulkan @asyrjasalo what to do? shall we publish? we didn't get any feedback actually maybe it's a no news good news :)

**Comment by bulkan** [comment]
@lucagiove just let me know and i can publish to PyPY

**Comment by Wolfe1** [comment]
Ready to update and test on my end once its in pypi. Im just lazy and rather have pip install it and travis run my unit tests haha.

**Comment by lucagiove** [comment]
@bulkan had some feedback on slack please proceed!!! :+1:

**Comment by ppodgorsek** [comment]
Why was this task closed? Pip still doesn't have version 0.6.2 unfortunately.

**Comment by bulkan** [comment]
Published now.

**Comment by ppodgorsek** [comment]
Thank you! :)
