### ISSUE TITLE
Post with data and header but display as '<empty>' or 'None' in the log file

### ISSUE THREAD

**Issue by Wolfe1** [bulkan/robotframework-requests#249]
One of the users of our automation framework is running into this confusing log when calling a POST request. Even-though header and data information is sent the log from RequestLibrary will come back and empty or None:

`
Post Request using : alias=postapi, uri=/apis/360facility/v1/assetclasses, data=<empty>, headers=None, files=None, allow_redirects=True 
`

I believe this is the same issue that was in #155 that was supposedly fixed some time ago.

**Comment by lucagiove** [comment]
could you verify what version of the library are you using?

**Comment by Wolfe1** [comment]
Ah my mistake, it seems he (any myself) were still on version 0.5.0. The latest version takes care of this. 

Sorry about that.

**Comment by lucagiove** [comment]
no problem ;) thanks
