### ISSUE TITLE
Cannot find requests_ntlm library

### ISSUE THREAD

**Issue by mmikirtumov** [bulkan/robotframework-requests#250]
We try to use request_ntlm_library, but the library throws an error.
Cannot find the request_ntlm library.
I think it will be better to add dependency in requirements.txt

**Comment by rea78** [comment]
Hi Guys, the keyword doc library still doesn't work.

**Comment by bulkan** [comment]
@rea78 you mean this https://bulkan.github.io/robotframework-requests/ ?

**Comment by lucagiove** [comment]
Here it is https://bulkan.github.io/robotframework-requests/doc/RequestsLibrary.html

**Comment by lucagiove** [comment]
@rea78 I don't see the relationship with this issue
