### ISSUE TITLE
${EMPTY} is being treated as "" rather than a 'blank' past version 0.5.0

### ISSUE THREAD

**Issue by Wolfe1** [bulkan/robotframework-requests#259]
We have been having issues moving past version 0.5.0 due to some more verbose messaging that is happening after upgrading.

![image](https://user-images.githubusercontent.com/3010366/73397419-1ce69080-42a9-11ea-8862-b83bddded644.png)

Any idea what triggers this additional logging and is there any way to suppress it? 

I noticed that in 0.6.2 you say that:
> response is logged if standard python/robotframework debug level is enabled (might be verbose)
Not sure if that is related but for us we are using the default log level of INFO.

Any assistance would be greatly appreciated, thanks.

**Comment by lucagiove** [comment]
Could you run with trace log level and provide the log.html file? make sure to anonymize your data before, a screenshot of the log.html without sensitive data might be a good choice.

**Comment by lucagiove** [comment]
Could you provide also the python and requests version?

**Comment by lucagiove** [comment]
Looking carefully at your output seems that you're comparing two arrays the first part is fine but the second has more detail.
You might compare only the first part of the array but this really depends on what you what to test.

**Comment by Wolfe1** [comment]
Python 3.6.3
Requests 2.22.0

In trying to get you an anonymized log I think I found our problem. When capturing the traffic in Fiddler it seems that after version 0.5.0 robotframework-requests is treating ${EMPTY} as "" where before it was an actual blank.

Call:
![image](https://user-images.githubusercontent.com/3010366/73470493-9a63dc80-434d-11ea-94ed-03bc893e8a96.png)

Version 0.6.2/0.6.3:
![image](https://user-images.githubusercontent.com/3010366/73470233-288b9300-434d-11ea-9721-eb23395bb484.png)

Version 0.5.0:
![image](https://user-images.githubusercontent.com/3010366/73470403-730d0f80-434d-11ea-8f61-2f48bf7e9c65.png)

**Comment by Wolfe1** [comment]
Still digging but I found the line that started this, line 1119 in RequestKeywords.py:
`merged_headers = session.headers.copy()`
which used to be:
`merged_headers = headers.copy()`

So now when this code executes it sees it as application/json for formatting which now takes us to:

```
def _format_data_according_to_header(self, session, data, headers):
        # Merged headers are already case insensitive
        headers = self._merge_headers(session, headers)

        if data is not None and headers is not None and 'Content-Type' in headers and not self._is_json(data):
            if headers['Content-Type'].find("application/json") != -1:
                if not isinstance(data, types.GeneratorType):
                    data = json.dumps(data)
            elif headers['Content-Type'].find("application/x-www-form-urlencoded") != -1:
                data = self._utf8_urlencode(data)
        else:
            data = self._utf8_urlencode(data)

        return data
```

Now that its considered JSON the empty data is converted into ""
![image](https://user-images.githubusercontent.com/3010366/73494277-d6149b80-4379-11ea-8616-6c2fe13e783e.png)

To prevent this I suggest the following pull request: #260 as per suggestions here:
https://stackoverflow.com/a/30137396/2283279

The potential exception if data = None is already taken care of in line 1059 so it shouldn't be an issue.

**Comment by lucagiove** [comment]
Hello @Wolfe1 thanks to your hint I was studying the code and this is the commit where I introduced much of the logic change in headers handling:
2499642340231c4102e4fd6ee77ba9de08a90b4e

Basically before default headers had the priority over local headers so local content-type was ignored and now it's not.
Do you think my change is correct?

Another thing I'm thinking that I'm not sure if data should be encoded to json without the user knowing... I mean there is json= parameter to explicitly pass a json as body.
If you want to test a case where headers are application/json and body not properly formatted?
The original requests library is not behaving like this, and by the way if you pass an empty string to json it gets json dumped..

```
resp = requests.post("http://localhost:5000/anything", data="", headers={'content-type': 'application/json'})
resp.content
b'{"args":{},"data":"","files":{},"form":{},"headers":{"Accept":"*/*","Accept-Encoding":"gzip, deflate","Connection":"keep-alive","Content-Length":"0","Content-Type":"application/json","Host":"localhost:5000","User-Agent":"python-requests/2.22.0"},"json":null,"method":"POST","origin":"127.0.0.1","url":"http://localhost:5000/anything"}\n'
resp = requests.post("http://localhost:5000/anything", json="", headers={'content-type': 'application/json'})
resp.content
b'{"args":{},"data":"\\"\\"","files":{},"form":{},"headers":{"Accept":"*/*","Accept-Encoding":"gzip, deflate","Connection":"keep-alive","Content-Length":"2","Content-Type":"application/json","Host":"localhost:5000","User-Agent":"python-requests/2.22.0"},"json":"","method":"POST","origin":"127.0.0.1","url":"http://localhost:5000/anything"}\n'
```
I'm interested in your opinion, maybe in the future version I'll remove the automatic data encoding, I'll discuss this with the community.

**Comment by Wolfe1** [comment]
@lucagiove I believe your change to use the local content-type over the session is correct but I am in no means an expert there. On my end we simply set the content-type in the session and make our call but we are using a new session each time:
![image](https://user-images.githubusercontent.com/3010366/73665586-f63ca700-4666-11ea-971a-0d0341252307.png)

I personally haven't used the json= parameter but that does seem like the correct way to do this...though it would require some rework on my end (and probably many others) once it was removed. Simply because many im sure have been relying on this functionality.

**Comment by lucagiove** [comment]
Ok I think I'm going to merge your PR since this is by the way a regression in the 0.5 behavior.
We'll see what to do in the future when/if this keywords will be deprecated since I'm not convinced about encoding data automatically based on the header.
