### ISSUE TITLE
Add support for new type of request OPTIONS, TRACE, PATCH

### ISSUE THREAD

**Issue by IlfirinPL** [bulkan/robotframework-requests#26]
Add support for new type of request OPTIONS, TRACE, PATCH

**Comment by vkosuri** [comment]
@bulkan Options and PATCH methods are done, does TRACE method required?
They said the method was weird https://github.com/kennethreitz/requests/pull/1345

**Comment by bulkan** [comment]
If requests doesn't support TRACE then we don't need to worry about it either.

**Comment by vkosuri** [comment]
Thank you very much
