### ISSUE TITLE
Support for Put request with files and Content-Type multipart/form-data

### ISSUE THREAD

**Issue by kerbam** [bulkan/robotframework-requests#29]
I have a server that requires files sent over a Put request to update files on the server side. Any chance of supporting files being sent over put, similar to the Post request or is there a way to send them currently? I'm not sure if this is an issue with the framework, but I know this type of request works in other applications (SoapUI and Jmeter). Test case is below. 
```Robotframework
Verify Update of a Benchmark
     [Documentation]             Verify the update benchmark functionality
     ${headers}=                 Create Dictionary    Content-Type    multipart/form-data
     ${info_content}=            Local.Get File    ${CURDIR}/../resources/benchmarkInfoUpdate.xml
     ${xccdf_content}=           Local.Get File    ${CURDIR}/../resources/sample-xccdf.xml
     ${oval_content}=            Local.Get File    ${CURDIR}/../resources/sample-oval.xml
     ${data}=                    Create Dictionary    benchmarkInfo    ${info_content}    xccdf    ${xccdf_content}    oval    ${oval_content}
     ${update_benchmark}=        HTTP.Put   ${FQDN}   /compliance/api/benchmark/${SAMPLE_ID.text}   data=${data}   headers=${headers} 
     Log To Console              ${update_benchmark.content}
     Should Be Equal As Strings  ${update_benchmark.status_code}    200
     ${update_id}=               Get Element    ${update_benchmark.content}    id
     Should Be Equal As Strings  ${update_id.text}    xccdf_com.vce._benchmark_sample    msg= Benchmark ids do not match ${update_id.text}!/n${SAMPLE_ID.text}
```

**Comment by vkosuri** [comment]
@bulkan can i submit PR on this issue?

**Comment by bulkan** [comment]
@vkosuri sure you can :)

**Comment by vkosuri** [comment]
It seems to me requests doesn't support **PUT request with Content-Type multipart/form-data**, More information see this thread https://github.com/kennethreitz/requests/issues/1081

Other alternative are list here

http://docs.python-requests.org/en/latest/user/quickstart/#post-a-multipart-encoded-file

http://stackoverflow.com/questions/12385179/how-to-send-a-multipart-form-data-with-requests-in-python

**Comment by vkosuri** [comment]
An example here

pybot  -L DEBUG:INFO --noncritical SKIP Requests_Tests.robot

```robot
Post Request With File
    [Tags]    post
    Create Session    httpbin    http://httpbin.org    debug=2    max_retries=10
    ${file_data}=    Get Binary File    ${CURDIR}${/}data.json
    ${files}=    Create Dictionary    file    ${file_data}
    ${resp}=    Post    httpbin    /post    files=${files}
    ${file}=    To Json    ${resp.json()['files']['file']}
    Dictionary Should Contain Key    ${file}    one
    Dictionary Should Contain Key    ${file}    two
```
Debug header displays, let me know if you required any further help.

![http-multipart](https://cloud.githubusercontent.com/assets/13664257/12027727/1f4a6820-adf1-11e5-85f1-16975cfa0198.png)

**Comment by hello-ming** [comment]
This issue is not sovled, PUT method is still not working with Content-Type multipart/form-data

**Comment by vkosuri** [comment]
@hello-ming could you please share a sample failing testcase of this issue?

**Comment by vkosuri** [comment]
@hello-ming i am closing this issue. Please fell free to reopen if you have any further updates.

**Comment by Formartha** [comment]
Hi, I'm stuck as well..

I can't send any file using put with multipart/form-data (even with using separator).
What do we need in order to strive to solve it?
