### ISSUE TITLE
request for additional functionality

### ISSUE THREAD

**Issue by merrittr** [bulkan/robotframework-requests#54]
could you add a method like the following to allow Digest authentication?

edit
/usr/local/lib/python2.7/dist-packages/RequestsLibrary/RequestsKeywords.py
to expose the HTTPDigestAuth:

    def create_digest_session(self, alias, url, auth, headers={}, cookies=None, timeout=None, proxies=None, verify=False):
       digest_auth = requests.auth.HTTPDigestAuth(*auth) if auth else None
       return self._create_session(alias, url, headers, cookies, digest_auth, timeout, proxies, verify)

**Comment by bulkan** [comment]
Pull requests welcome

**Comment by vkosuri** [comment]
@bulkan can i work on this?

**Comment by merrittr** [comment]
Hi Bulkan 

I just saw this close msg Id like to merge in , I honestly don't know where to start is vkosuri doing it?

**Comment by oleduc** [comment]
@merrittr The PR was merged but was not included in any release. We need @bulkan to create a release in order to have #76 in production.

**Comment by bulkan** [comment]
I just pushed `0.4.0` to PyPI
