### ISSUE TITLE
Fail to import RequestLibrary in ride editor 

### ISSUE THREAD

**Issue by ShashwatDubey** [bulkan/robotframework-requests#55]
I have installed RequestsLibrary using following command - pip install -U robotframework-requests and have added the same in my environment variable and then tried to import in ride editor.

but somehow its not working and coming in RED color which means, there is some error, may be in installation or configuration. At the same, i tried similar steps with another robot library and it was working fine.
so, please help me to install or let me if i need to perform any additional steps.

**Comment by bulkan** [comment]
@ShashwatDubey is related to #44  ?

**Comment by ShashwatDubey** [comment]
Got it.
Now i am able to use it. 
Thanks @bulkan 

Also, can you please help me help with a sample test case for using POST request ?

**Comment by bulkan** [comment]
No problem.

https://github.com/bulkan/robotframework-requests/blob/master/tests/testcase.txt#L49
