### ISSUE TITLE
AttributeError: 'unicode' object has no attribute 'items'

### ISSUE THREAD

**Issue by huyentruong** [bulkan/robotframework-requests#65]
Hi,
I don't have a request API testing experience so I am new in this field.
I am trying to post a request which contains huge data in input xml
I have created a testcase for post

Create Session	httpbin aaa		
${resp}=	Post	httpbin		'Content-Type':'application/xml'
Should Be Equal As Strings	${resp.status_code}	200		

When I am trying to run the test case, getting error as "AttributeError: 'unicode' object has no attribute 'items'".

Can you figure out the problem?

Thanks in advance.

**Comment by bulkan** [comment]
Not quite sure what's wrong. Can you share your test  in a better format ? Maybe in a gist.github.com ?

**Comment by huyentruong** [comment]
Yes, I am trying to post a request which contains data in input xml but it failed. Please help me. My target is get content of request to save into a variable and use this variable to compare result. But 
I have just created a testcase for post request as below link 

https://gist.github.com/huyentruong/fb4bfd816dd70fd01508

When I am trying to run the test case, getting error as ${resp} = <Response [400]>

Can you please figure out the problem?

Thanks in advance.

**Comment by bulkan** [comment]
I believe this line is the problem; 

https://gist.github.com/huyentruong/fb4bfd816dd70fd01508#file-gistfile1-txt-L8

what is the content-type of the response ?

**Comment by huyentruong** [comment]
When I removed two last sentences, it doesn't work. It received response 400.

And content-type of the response is application/xml

**Comment by oleduc** [comment]
You can parse ${resp.content} with an XML parser and assign the result to a variable.

http://robotframework.org/robotframework/latest/libraries/XML.html

**Comment by huyentruong** [comment]
Thanks oleduc.

I still get response 400 from post request so i can not get content of http response :(

**Comment by oleduc** [comment]
There might be many reasons why you get a 400 response. You have to look at the message the server is giving you. That said, you can try specifying the charset in the header's Content-Type.

Also, why are you passing the dictionary as a file? Can't you simply send the payload as data?

${resp}=	Post Request	CatalogWS	/ValidateItemInfo/MCKWHEADEVQA	data=${files}	headers=${headers}

If you use files instead of data, then the content the dict in ${files} will be transmitted using multipart/form-data; which might not be understood by the service you are consuming.

**Comment by huyentruong** [comment]
Yes, I updated my test case in the below link:
https://gist.github.com/huyentruong/fb4bfd816dd70fd01508

And I got the error message: AttributeError: 'unicode' object has no attribute 'items' :(

**Comment by oleduc** [comment]
Something that should be iterable is actualy a unicode string.
Headers should be iterable. So maybe:

${headers}=    Create Dictionary    Content-Type=application/xml	
${resp}=    Post Request    CatalogWS    /ValidateItemInfo/MCKWHEADEVQA    data=${files}    headers=${headers}

**Comment by huyentruong** [comment]
@oleduc thank you so much

**Comment by oleduc** [comment]
@huyentruong No problem ;)

**Comment by huyentruong** [comment]
@bulkan thank you. I solved my problem.

**Comment by bulkan** [comment]
thanks @oleduc for helping out :)

**Comment by NadeemMohammad** [comment]
@oleduc
You can declare header as a dictionary variable.

&{headers}=   Content-Type=application/xml
