### ISSUE TITLE
Resetting dropped connection

### ISSUE THREAD

**Issue by vkosuri** [bulkan/robotframework-requests#67]
Hi,

I am frequently getting Resetting dropped connection from my UUT, are we reusing the same HTTP session?

Any other methods to avoid this this error?

A snapshot from robot test log

![resettingdropped](https://cloud.githubusercontent.com/assets/13664257/11488573/990aaebe-97ed-11e5-94c5-9cee717203a3.png)

Thanks
Malli

**Comment by bulkan** [comment]
Which version of robotframework-requests are you using ?

**Comment by vkosuri** [comment]
VERSION = '0.3.9'

**Comment by bulkan** [comment]
Thanks. Thats the latest release. 

We dont [reuse sessions](https://github.com/bulkan/robotframework-requests/blob/master/src/RequestsLibrary/RequestsKeywords.py#L58).

Not sure why you are getting that error. Try with a bigger request timeout ?

**Comment by vkosuri** [comment]
It came from urllib https://github.com/shazow/urllib3/blob/master/urllib3/connectionpool.py#L240

Not to do any with this package because it's uses internally 

> robot requests -> requests -> urllib3

urllib3 snippet

```Python
# If this is a persistent connection, check if it got disconnected
        if conn and is_connection_dropped(conn):
            log.info("Resetting dropped connection: %s" % self.host)
            conn.close()
            if getattr(conn, 'auto_open', 1) == 0:
                # This is a proxied connection that has been mutated by
                # httplib._tunnel() and cannot be reused (since it would
                # attempt to bypass the proxy)
                conn = None
```
