### ISSUE TITLE
Is it possible to add http debugger information for every operation

### ISSUE THREAD

**Issue by vkosuri** [bulkan/robotframework-requests#68]
Hi

We are sending huge number of requests to NE, Sometimes it is very difficulty to find what inforamtion sent from client to server, 

Is there any possibility add looger debug information for every input operation?

I found a example located for python requests

http://docs.python-requests.org/en/master/api/#api-changes

``` Python
import requests
import logging

# these two lines enable debugging at httplib level (requests->urllib3->httplib)
# you will see the REQUEST, including HEADERS and DATA, and RESPONSE with HEADERS but without DATA.
# the only thing missing will be the response.body which is not logged.
import httplib
httplib.HTTPConnection.debuglevel = 1

logging.basicConfig() # you need to initialize logging, otherwise you will not see anything from requests
logging.getLogger().setLevel(logging.DEBUG)
requests_log = logging.getLogger("requests.packages.urllib3")
requests_log.setLevel(logging.DEBUG)
requests_log.propagate = True

requests.get('http://httpbin.org/headers')
```
More inforamtion https://docs.python.org/2/library/httplib.html#httplib.HTTPConnection.set_debuglevel

Thanks
Malli

**Comment by bulkan** [comment]
Sure thing submit a pull request.
