### ISSUE TITLE
Post request fail in 0.3.9 but success in 0.3.8

### ISSUE THREAD

**Issue by wind-chh** [bulkan/robotframework-requests#71]
This is my case lines in Robot,
${policy_data} = BuiltIn.Set Variable {"jsonType":"networkpolicy","ownerId":${ownerId},"name":"${name}","description":"${desc}","type":"NetworkAccessAndSwitching"}
${output} = RequestsLibrary.Post Request new-policy, /services/config/policy/networkpolicies, headers=${headers}, data=${policy_data}

my case worked in 0.3.8, but failed in 0.3.9. I think it maybe the unicode string cause this problem.

**Comment by vkosuri** [comment]
Try this

``` Robot
${policy_data} =  Evaluate  {"jsonType":"networkpolicy","ownerId":${ownerId},"name":"${name}","description":"${desc}","type":"NetworkAccessAndSwitching"}
${output} = RequestsLibrary.Post Request new-policy, /services/config/policy/networkpolicies, headers=${headers}, data=${policy_data}
```

**Comment by vkosuri** [comment]
@wind-chh any updates?
