### ISSUE TITLE
TypeError: get_request() got an unexpected keyword argument

### ISSUE THREAD

**Issue by momacoy** [bulkan/robotframework-requests#82]
Encountered `TypeError: get_request() got an unexpected keyword argument` when url has a query parameter using the following environment:
```
$ pybot --version
Robot Framework 3.0 (Python 2.7.11 on linux2)
```
But not encountered in the following enviroment:
```
>pybot --version
Robot Framework 2.9.2 (Python 2.7.10 on win32)
```
Code:
```
*** Settings ***
Test Setup		Create Gateway Session

*** Keywords ***
Create Gateway Session
	Create Session			gateway			${GATEWAY}

*** Test Cases ***
Get Categories
    ${resp}=						Get Request			    gateway		/category
    Should Be Equal As Strings		${resp.status_code}		200
    
Get Categories with pageSize
    ${resp}=						Get Request			    gateway		/category?pageSize=1
    Should Be Equal As Strings		${resp.status_code}		200
```

Log:
```
$ pybot test.robot 
==============================================================================
Test :: Test                                                                  
==============================================================================
Get Categories                                                        | PASS |
------------------------------------------------------------------------------
Get Categories with pageSize                                          | FAIL |
TypeError: get_request() got an unexpected keyword argument '/category?pageSize'
------------------------------------------------------------------------------
Test :: Test                                                          | FAIL |
2 critical tests, 1 passed, 1 failed
2 tests total, 1 passed, 1 failed
==============================================================================
```

Is there a workaround for this?

**Comment by vkosuri** [comment]
you are trying to use both url and params instead use

```
Get Request    / category   params='pazeSize=1'
```

**Comment by momacoy** [comment]
@vkosuri Thanks! the workaround works.

The version used for `windows` and `linux` are different:
`windows: requests-2.8.1` , `linux: requests-2.9.1`

**Comment by vkosuri** [comment]
@momacoy thank you, More information passing params, http://docs.python-requests.org/en/latest/user/quickstart/#passing-parameters-in-urls

>You often want to send some sort of data in the URL’s query string. If you were constructing the URL by hand, this data would be given as key/value pairs in the URL after a question mark, e.g. httpbin.org/get?key=val. Requests allows you to provide these arguments as a dictionary, using the params keyword argument. As an example, if you wanted to pass key1=value1 and key2=value2 to httpbin.org/get, you would use the following code:

**Comment by momacoy** [comment]
@vkosuri Thanks a lot!
