### ISSUE TITLE
Retry decorator consumes so much time when we have large number of requests from unit

### ISSUE THREAD

**Issue by vkosuri** [bulkan/robotframework-requests#83]
It seems to the retry decorator **consumes so much time when we have large number of requests from unit**, it is working fine if we have a small number requests.

Here some statistics i observed using robot profiler

With retry decorator statistics 

<pre>
1    0.000    0.000    0.000    0.000 RequestsKeywords.py:21(__init__)
  248    0.011    0.000  287.346    1.159 RequestsKeywords.py:217(patch_request)
102705    0.816    0.000    4.060    0.000 RequestsKeywords.py:25(_utf8_urlencode)
    4    0.000    0.000    0.002    0.000 RequestsKeywords.py:37(_create_session)
  469    0.008    0.000  431.145    0.919 RequestsKeywords.py:387(_get_request)
<b>101988    0.002    0.000  84256.164    0.809 RequestsKeywords.py:34(f_retry)</b>
101988    2.587    0.000 84456.164    0.828 RequestsKeywords.py:399(_post_request)
  248    0.009    0.000  287.253    1.158 RequestsKeywords.py:412(_patch_request)
</pre>

Instead I used ```requests``` retry [method](http://www.coglib.com/~icordasc/blog/2014/12/retries-in-requests.html), it was much faster than retry decorator

``` Python
    if max_retries > 0:
            a = requests.adapters.HTTPAdapter(max_retries=max_retries)
            s.mount('https://', a)
            s.mount('http://', a)
```
without retry decorator statistics 

``` Shell

        1    0.000    0.000    0.000    0.000 RequestsKeywords.py:21(__init__)
      248    0.011    0.000  287.346    1.159 RequestsKeywords.py:217(patch_request)
   102705    0.816    0.000    4.060    0.000 RequestsKeywords.py:25(_utf8_urlencode)
        4    0.000    0.000    0.002    0.000 RequestsKeywords.py:37(_create_session)
      469    0.008    0.000  431.145    0.919 RequestsKeywords.py:387(_get_request)
   101988    2.587    0.000 84456.164    0.828 RequestsKeywords.py:399(_post_request)
      248    0.009    0.000  287.253    1.158 RequestsKeywords.py:412(_patch_request)
```

@bulkan could you please comment on this?

**Comment by oleduc** [comment]
@vkosuri Hi, the current implementation of the retry operator is using time.sleep which locks the thread for the given period of time. 

I'm not sure why we use our own implementation instead of the one already bundled with requests. We might want to revert that.
