### ISSUE TITLE
Verify parameter should accept String value

### ISSUE THREAD

**Issue by Mogztter** [bulkan/robotframework-requests#91]
Requests library allow to configure the CA bundle file or directory with certificates of trusted CAs with the `verify` parameter: http://docs.python-requests.org/en/latest/user/advanced/#ssl-cert-verification

In the `_create_session` function, the `verify` parameter is converted to boolean: https://github.com/bulkan/robotframework-requests/blob/master/src/RequestsLibrary/RequestsKeywords.py#L129

I think we should allow `verify` parameter to be a String value to be able to configure CA bundle.

**Comment by vkosuri** [comment]
@Mogztter Are you interested work on this issue? If so could you submit PR for this issue?

**Comment by Mogztter** [comment]
Done :smile:
