### ISSUE TITLE
Version 0.4.1 or 0.5.0 ?

### ISSUE THREAD

**Issue by bulkan** [bulkan/robotframework-requests#94]
Hi @vkosuri & @oleduc ,

I was about to publish a new version to PyPI but not sure which version number I should go with. 

Was #86 a major or minor issue ?

Also @oleduc yes I would like it if you guys can help out here as I don't use RF anymore.

**Comment by oleduc** [comment]
I say 0.4.1 as we didn't implement any major features. And great, we use RF and rf-requests very heavily at my workplace and we will continue to do so for the foreseeable future.

**Comment by vkosuri** [comment]
@bulkan i agreed with @oleduc will go with 0.4.1 before that we need finish below tasks

- [ ] Pending PRs
- [ ] testcase updation with latest changes
- [ ] gh-pages updation

**Comment by bulkan** [comment]
@oleduc Thanks !

I've pushed 0.4.1 to PyPI. I can always create another release when we merge more of the  PR's
